def palabrasClave():  
    diccionarioBusqueda = { 
                            "Rollo de Justicia de Redecilla del Camino" : "Rollo Justicia Redecilla Camino",
                            "Palacio Fortificado de Castildelgado" : "Palacio Fortificado Castildelgado",
                            "Castillo de Belorado" : "Castillo Belorado",
                            "Ruinas de la Iglesia de San Félix de Villafranca Montes de Oca" : "Ruinas Iglesia San Félix Villafranca Montes Oca",
                            "Monasterio de San Juan de Ortega" : "Monasterio San Juan Ortega",
                            "Sierra de Atapuerca" : "Sierra Atapuerca",
                            "Cueva del Silo de Ibeas de Juarros" : "Cueva Silo Ibeas Juarros",
                            "Cueva mayor Portalon de entrada Ibeas de Juarros" : "Cueva Mayor portalon entrada Ibeas Juarros",
                            "Cueva Mayor Principal Salon de Coro de Ibeas de Juarros" : "Cueva Mayor salon coro Ibeas Juarros",
                            "Casco histórico de la Ciudad de Burgos" : "Casco historico Burgos",
                            "Archivo Historico Provincial de Burgos" : "Archivo Historico provincial Burgos",
                            "Biblioteca Pública de Burgos" : "Biblioteca publica Burgos",
                            "Castillo de Burgos" : "Arquitectura Castillo Burgos",
                            "Muralla de Burgos" : "Muralla Burgos",
                            "Torre de Albillos de Burgos" : "Torre Albillos Burgos",
                            "Torre de San Zoles de Burgos" : "Torre San Zoles Burgos",
                            "Crucero Calle Nuño Rasura de Burgos" : "Crucero Calle Nuño Rasura Burgos",
                            "Crucero Gamonal Rio Pico de Burgos" : "Crucero Gamonal Rio Pico Burgos",
                            "Crucero Plaza del Rey de Burgos" : "Crucero Plaza Rey Burgos",
                            "Arco de Santa Maria de Burgos" : "Arco Santa Maria Burgos",
                            "Cartuja de Santa Maria de Miraflores de Burgos" : "Cartuja Santa Maria Miraflores Burgos",
                            "Casa del Cordon de Burgos" : "Casa Cordon Burgos",
                            "Casa Miranda de Burgos" : "Casa Miranda Burgos",
                            "Museo de Burgos" : "Museo Burgos",
                            "Conjunto del Monasterio de San Juan de Burgos" : "Monasterio San Juan Burgos",
                            "Consulado del mar de Burgos" : "Consulado Mar Burgos",
                            "Hospital de la Concepcion de Burgos" : "Hospital Concepcion Burgos",
                            "Hospital del rey de Burgos" : "Hospital Rey Burgos",
                            "Iglesia Catedral de Santa Maria de Burgos" : "Catedral Burgos",
                            "Iglesia de San Esteban de Burgos" : "Iglesia San Esteban Burgos",
                            "Iglesia de San Gil de Burgos" : "Iglesia San Gil Burgos",
                            "Iglesia de San Nicolas de Bari de Burgos" : "Iglesia San Nicolas Burgos",
                            "Iglesia de Santa Maria de Burgos" : "Iglesia Antigua Burgos",
                            "Monasterio de Santa Maria la Real de las Huelgas de Burgos" : "Monasterio Huelgas Burgos",
                            "Museo del real Monasterio de la Huelgas de Burgos" : "Museo Huelgas Burgos",
                            "Palacio Angulo de Burgos" : "Palacio Angulo Burgos",
                            "Palacio del Paseo de la Isla de Burgos" : "Palacio Isla Burgos",
                            "Puerta de San Esteban de Burgos" : "Puerta San Esteban Burgos",
                            "Real Monasterio de San Agustin de Burgos" : "Monasterio San Agustin Burgos",
                            "Teatro Principal de Burgos" : "Teatro Principal Burgos",
                            "Crucero de Tardajos" : "Crucero Tardajos",
                            "Yacimiento de Deobrigula de Tardajos " : "Yacimiento Deobriguda Tardajos ",
                            "Crucero de Hontanas" : "Crucero Hontanas",
                            "Torreon de Hontanas" : "Torreon Hontanas",
                            "La Villa de Castrojeriz" : "Castrojeriz",
                            "Casa Gutierrez Barona o el Fuerte de Castrojeriz" : "Casa Barona Castrojeriz",
                            "Castillo de Castrojeriz" : "Castillo Castrojeriz",
                            "La Torre de Castrojeriz" : "Torre Castrojeriz",
                            "Murallas de Castrojeriz" : "Murallas Castrojeriz",
                            "Iglesia Colegiata Santa Maria del Manzano de Castrojeriz" : "Colegiata Santa Maria Castrojeriz",
                            "Iglesia de San Juan de Castrojeriz" : "Iglesia San Juan Castrojeriz",
                            "Rollo de Justicia de Itero de la Vega " : "Rollo Justicia Itero Vega ",
                            "Canal de Castilla de Boadilla del Camino" : "Canal Castilla Boadilla Camino",
                            "Iglesia Parroquial de Nuestra Señora de la Asuncion de Boadilla del Camino" : "Iglesia Asuncion Boadilla Camino",
                            "Rollo de Justicia de la Villa de Boadilla del Camino" : "Rollo Boadilla Camino",
                            "Canal de Castilla de Fromista" : "Canal Castilla Fromista",
                            "Iglesia de San Martin de Fromista" : "Iglesia San Martin Fromista",
                            "Iglesia de Santa Maria del Castillo de Fromista" : "Iglesia Santa Maria Fromista",
                            "Iglesia de Santa Maria la Blanca de Villacazar de Sirga" : "Santa Maria Blanca Villacazar Sirga",
                            "Iglesia de Santa Maria de Carrion de los Condes" : "Iglesia Santa Maria Carrion Condes",
                            "Iglesia de Santiago de Carrion de los Condes" : "Iglesia Santiago Carrion Condes",
                            "Monasterio de San Zoilo de Carrion de los Condes" : "Monasterio San Zoilo Carrion",
                            "Dos Tejidos Medievales del Monasterio de San Zoilo de Carrion de los Condes" : "Tejidos Medievales Carrion Condes",
                            "Casa del General San Martin de Cervatos de la Cueza" : "Casa General San Martin Cervatos",
                            "Iglesia de San Fructuoso de Villada" : "San Fructuoso Villada",
                            "La Villa de Grajal de Campos" : "Grajal Campos",
                            "Castillo de Grajal de Campos" : "Castillo Grajal Campos",
                            "Palacio de los Condes de Grajal de Campos" : "Palacio Condes Grajal Campos",
                            "La Villa de Sahagún" : "Villa Sahagún",
                            "Las Murallas de Sahagún" : "Murallas Sahagún",
                            "Iglesia de la Peregrina de Sahagún" : "Iglesia Peregrina Sahagún",
                            "Iglesia de San Tirso de Sahagún" : "Iglesia san Tirso Sahagún",
                            "Ruinas del Monasterio de San Facundo de Sahagún" : "Ruinas San Facundo Sahagún",
                            "Ruinas San Primitivo de Sahagún" : "Ruinas San Primitivo Sahagún",
                            "Iglesia de San Lorenzo de Sahagún" : "Iglesia San Lorenzo Sahagún",
                            "Horreo de Mansilla de Mansilla de las Mulas" : "Horreo Mansilla Mulas",
                            "Recinto Murado de Mansilla de las Mulas" : "Murallas Mansilla Mulas",
                            "Yacimiento Arqueologico de Villamoros de Mansilla" : "Yacimiento Arqueologico Antigua Ciudad Lancia",
                            "Monasterio de Santa Maria de Sandoval de Villaverde de Sandoval" : "Monasterio Santa Maria Sandoval",
                            "Determinadas Zonas de la Ciudad de Leon" : "Casco historico Leon",
                            "Archivo Historico Provincial de Leon" : "Archivo Historico Provincial Leon",
                            "Biblioteca Pública de Leon" : "Biblioteca Publica Leon",
                            "Castillo de Leon" : "Arquitectura Castillo Leon",
                            "Horreo de Leon" : "Horreo Leon",
                            "Locomotora English Electric de Leon" : "Locomotora English Electric Leon",
                            "Locomotora Mikado de Leon" : "Locomotora Mikado Leon",
                            "Casa de botines de Leon" : "Casa Botines Leon",
                            "Casa Palacio de Fernandez Cadorniga de Leon" : "Casa Palacio Fernandez Cadorniga Leon",
                            "Catedral de Santa Maria de Leon" : "Catedral Leon",
                            "Convento de San Marcos de Leon" : "Convento San Marcos Leon",
                            "Edificio Neomudejar de Leon " : "Edificio Neomudejar Leon",
                            "Fabrica de productos Quimicos Abello de Leon" : "Fabrica Abello Leon",
                            "Fachada de la Casa de las Carnicerias de Leon" : "Fachada Casa Carnicerias Leon",
                            "Hotel Alfonso V de Leon" : "Hotel Alfonso V Leon",
                            "Iglesia de San Salvador de Palat del Rey" : "Iglesia San Salvador Palat Rey",
                            "Iglesia de Santa Maria del Camino o Mercado de Leon" : "Iglesia Santa Maria Camino Mercado Leon",
                            "Iglesia Colegiata de Leon" : "Colegiata San Isidoro Leon",
                            "Palacio de los Guzmanes de Leon" : "Palacio Guzmanes Leon",
                            "Palacio del Conde Luna de Leon" : "Palacio Conde Luna Leon",
                            "Recinto de las Murallas de Leon" : "Murallas Leon ",
                            "Torreon de San Pelayo de Leon" : "Torreon San Pelayo Leon",
                            "Crucero de Trobajo del Camino" : "Crucero Trobajo Camino",
                            "Crucero del Mirador de la Cruz de San Andrés del Rabanedo" : "Crucero Mirador Cruz San Andrés Rabanedo",
                            "Santuario de la Virgen del Camino" : "Santuario Virgen Camino Leon",
                            "Horreo Valverde de Valverde de la Virgen" : "Horreo Valverde Virgen",
                            "Puente Antiguo de Hospital de orbigo" : "Puente Hospital Orbigo",
                            "Crucero de Santo Toribio de San Justo de la Vega" : "Crucero Santo Toribio San Justo Vega",
                            "Calzada de la Plata en Castilla y Leon de Astorga" : "Calzada Plata Astorga",
                            "La Cuidad de Astorga" : "Cuidad Astorga",
                            "Las Murallas de Astorga" : "Murallas Astorga",
                            "Ayuntamiento de Astorga" : "Ayuntamiento Astorga",
                            "Catedral de Santa Maria de Astorga" : "Catedral Astorga",
                            "Ergastula Romana de Astorga" : "Ergastula Astorga",
                            "Palacio Episcopal de Astorga" : "Palacio Episcopal Astorga",
                            "Iglesia Parroquial de la Asuncion de Rabanal del Camino" : "Iglesia Rabanal Camino",
                            "La Villa de Molinaseca" : "Villa Molinaseca",
                            "El Casco Antiguo de Ponferrada" : "Casco Antiguo Ponferrada",
                            "Castillo de El Temple de Ponferrada" : "Castillo Temple Ponferrada",
                            "Yacimiento Arqueologico La Edrada de Cacabelos" : "Yacimiento Arqueologico Edrada",
                            "El Castro de la Ventosa de Pieros" : "Castro Ventosa Pieros",
                            "Zona Antigua de Villafranca del Bierzo" : "Zona Antigua Villafranca Bierzo",
                            "Castillo de Villafranca del Bierzo" : "Castillo Villafranca Bierzo",
                            "Colegiata de Santa Maria de Villafranca del Bierzo" : "Colegiata Villafranca Bierzo",
                            "Iglesia de San Francisco de Asis de Villafranca del Bierzo" : "Iglesia San Francisco Asis Villafranca Bierzo",
                            "Iglesia de San Juan o de San Fiz de Villafranca del Bierzo" : "Iglesia San Juan San Fiz Villafranca Bierzo",
                            "Iglesia de San Nicolas el Real de Villafranca del Bierzo" : "Iglesia San Nicolas Real Villafranca Bierzo",
                            "Iglesia de Santiago de Villafranca del Bierzo" : "Iglesia Santiago Villafranca Bierzo",
                            "Castillo de Sarracin de Vega de Valcarce" : "Castillo Sarracin Vega Valcarce",
                            "Horreos de Vega de Valcarce" : "Horreos Vega Valcarce",
                            "Horreos de La Laguna" : "Horreos La Laguna"        
                            }
    return diccionarioBusqueda